# Generated by Django 5.2.4 on 2025-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_author_name_alter_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('comments', models.ManyToManyField(related_name='tags', to='forum.comment')),
            ],
        ),
    ]
