# Generated by Django 5.2.4 on 2025-08-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20250807_0121'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE forum_notification RENAME COLUMN created_at TO old_created_at;",
            reverse_sql="ALTER TABLE forum_notification RENAME COLUMN old_created_at TO created_at;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE forum_notification ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();",
            reverse_sql="ALTER TABLE forum_notification DROP COLUMN created_at;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE forum_notification DROP COLUMN old_created_at;",
            reverse_sql="ALTER TABLE forum_notification ADD COLUMN old_created_at BOOLEAN;"
        ),
    ]
