# Generated by Django 5.2.4 on 2025-08-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='moisture',
            new_name='moisture_numeric',
        ),
    ]
